smart_home/devices/__init__.py
from .BaseDevice import Device, Command, LightDevice, BaseDevice, command

smart_home/routes.py
from smart_home import models, db
from flask import render_template, redirect, url_for, flash, request, Blueprint
from .forms import LoginForm, RegistrationForm, TokenForm, AddDeviceForm, StartTaskForm
from flask_login import current_user, login_user, logout_user
from flask_login import login_required
from werkzeug.urls import url_parse
from smart_home.auth import generate_qr_code
import pika
import json
from smart_home.devices.PI import PI
from flask import current_app

main_bp = Blueprint('main', __name__, static_folder="static", template_folder="templates")


@main_bp.route('/')
@main_bp.route('/index')
@login_required
def index():
    return render_template("index.html", title="Home", user="Admin")


@main_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = models.User.query.filter_by(username=form.username.data).first()
        if user is None or not user.check_password(form.password.data):
            flash('Invalid username or password')
            return redirect(url_for("main.login"))
        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get('next')
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for('main.index')
        return redirect(next_page)

    return render_template('login.html', title="Sign In", form=form)


@main_bp.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@main_bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = models.User(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Congratulations, you are now a registered user!')
        return redirect(url_for('main.login'))
    return render_template('register.html', title='Register', form=form)


@main_bp.route("/token", methods=['GET', 'POST'])
@login_required
def token():
    form = TokenForm()
    if form.validate_on_submit():
        token = current_user.generate_token(current_app.config["SECRET_KEY"])
        token = token.decode("utf-8")
        form.token = token
        qr_code = generate_qr_code(token)
        return render_template('app-token.html', title='Token', form=form, code=True)
    return render_template('app-token.html', title='Token', form=form)


@main_bp.route("/assistant", methods=['GET', 'POST'])
@login_required
def assistant():
    return render_template('assistant.html')


@main_bp.route('/user/<username>')
@login_required
def user(username):
    user = models.User.query.filter_by(username=username).first_or_404()
    posts = [
        {"author": user, "body": "Test Item #1"},
        {"author": user, "body": "Test Item #2"}
    ]
    return render_template('user.html', user=user, posts=posts)


@main_bp.route('/devices', methods=['GET', 'POST'])
@main_bp.route('/devices/<device_id>')
@login_required
def devices(device_id=None):
    form = AddDeviceForm()
    selected = device_id
    available_devices = models.Device.query.all()
    if form.validate_on_submit():
        device = models.Device(name=form.device_name.data, device_type=form.device_type.data, address=form.address.data)
        db.session.add(device)
        db.session.commit()
        available_devices = models.Device.query.all()
        form = AddDeviceForm()
        return render_template('devices.html', form=form, devices=available_devices)
    if device_id:
        print(device_id)
        return render_template('devices.html', form=form, devices=available_devices, selected=selected)

    return render_template('devices.html', form=form, devices=available_devices)


@main_bp.route('/pi', methods=['GET', 'POST'])
@login_required
def pi():
    pi = PI(device_id=1, name="main")

    return render_template('pi.html', pins=pi.pins)


@main_bp.route('/tasks', methods=['GET', 'POST'])
@login_required
def tasks():
    tasks = []
    form = StartTaskForm()
    if form.validate_on_submit():
        print("Adding task to queue")
        connection = pika.BlockingConnection()
        channel = connection.channel()
        if form.queue.data:
            channel.queue_declare(form.queue.data, durable=True)
        else:
            channel.queue_declare("tasks", durable=True)
        message = {
            "device": form.device.data,
            "command": form.command.data,
            "args": form.args.data
        }
        print(message)
        channel.basic_publish(exchange='',
                              routing_key='tasks',
                              body=json.dumps(message).encode("utf-8"))
        flash("Published Message")
        form = StartTaskForm()
        return render_template('tasks.html', form=form, tasks=tasks)

    return render_template('tasks.html', form=form, tasks=tasks)


@main_bp.route('/add_job/<cmd>')
@login_required
def add_job(cmd):
    connection = pika.BlockingConnection(pika.ConnectionParameters(host='rabbitmq'))
    channel = connection.channel()
    channel.queue_declare(queue='task_queue', durable=True)
    channel.basic_publish(
        exchange='',
        routing_key='task_queue',
        body=cmd,
        properties=pika.BasicProperties(
            delivery_mode=2,  # make message persistent
        ))
    connection.close()
    return " [x] Sent: %s" % cmd

smart_home/templates/app-token.html
{% extends "base.html" %}

{% block content %}
    <div id="token">
        <h2>Generate Application Token</h2>
        <form method="post" action="">
            {{ form.hidden_tag() }}
            <p>
                {{ form.token.label }}<br>
                {{ form.token}}
                {% for error in form.token.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
            <p>{{ qr_code }}</p>
            {% if code %}
                <img src="/static/qrcode_guest.png">
            {% endif %}

            <p>
                <p>{{ form.submit() }}</p>
            </p>
        </form>
    </div>
{% endblock %}

smart_home/templates/assistant.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h2>
            Voice Assistant
        </h2>
        <div class="container" id="voice-container">
            <audio>
                Listen
            </audio>
            <button onclick="activate_mic()">Activate</button>
        </div>
        <div class="container" id="assistant-history">

        </div>
    </div>
{% endblock %}
{% block final_script %}
    <script src="/static/js/assistant.js"></script>
<script type="text/javascript">
    function activate_mic() {
        const constraints = {
        audio: true
    };
        const audio= document.querySelector('audio')
        navigator.mediaDevices.getUserMedia(constraints).then((stream) => {audio.srcObject =stream} );
    }

</script>
{% endblock %}

smart_home/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="{{ url_for('static',filename='style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='sidebar.css') }}">
    {% block header %}
    {% endblock %}

</head>

<body>
    <script src="{{ url_for('static', filename='/scripts/jquery-3.5.1.js') }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% block script %}
    {% endblock %}

    <nav class="navbar sticky-top navbar-dark bg-dark justify-content-right">
        <a class="navbar-brand" href="#">SmartHome</a>
        <a class="navbar-nav" href="{{ url_for('main.index') }}">Home</a>
        {% if current_user.is_anonymous %}
        <a class="navbar-nav" href="{{ url_for('main.login') }}">Login</a>
        {% else %}

        <a class="navbar-nav" href="/user/{{ current_user.username }}">{{ current_user.username }}</a>
        <a class="navbar-nav"href="{{ url_for('main.logout') }}">Logout</a>
        {% endif %}
    </nav>


<div class="d-flex" id="wrapper">
    <!-- Sidebar -->
    <div class="bg-light border-right" id="sidebar-wrapper">
      <div class="list-group list-group-flush">
          <a href="{{ url_for('main.pi') }}" class="list-group-item list-group-item-action bg-light">Pi</a>
          <a href="{{ url_for('main.devices') }}" class="list-group-item list-group-item-action bg-light">Devices</a>
          <a href="/monitoring" class="list-group-item list-group-item-action bg-light">Monitoring</a>
          <a href="{{ url_for('main.assistant') }}" class="list-group-item list-group-item-action bg-light">Assistant</a>
          <a href="{{ url_for('main.tasks') }}" class="list-group-item list-group-item-action bg-light">Tasks</a>
        <a href="{{ url_for('main.token') }}" class="list-group-item list-group-item-action bg-light">Token</a>
          <!-- TODO show user section only to admins-->

        <a href="#" class="list-group-item list-group-item-action bg-light">Profile</a>

      </div>
    </div>

    <div id="content" class="container">
        {% block content %}

        {% endblock %}
        <hr>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul>
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% endwith %}

    </div>
</div>
{% block final_script %}
{% endblock %}
</body>
</html>

smart_home/templates/devices.html
{% extends 'base.html' %}

{% block content %}
    <script src="{{ url_for('static', filename='/js/devices.js') }}"></script>

    <div class="row">
        <div id="devices-list" class="col-sm-3">
            <div class="container border">
            <h2>Devices</h2>
            <div class="container-fluid">
                {% for device in devices %}

                    <div class="row device-item">
                        <div class="col-sm-4">
                            {{ device.name }}
                        </div>
                        <div class="col-sm-8">
                            {{ device.address }}
                            {{ device.device_type }}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        </div>

        <div class="col-sm-9">
            <div class="row">
                <div class="container border">
                <h2>Add device</h2>
                <form action="" method="post">
                    {{ form.hidden_tag() }}
                    <div class="container">
                        <div class="row device-row">
                            <div class="col-sm-4">
                                {{ form.device_name.label }}
                            </div>
                            <div class="col-sm-8">
                                {{ form.device_name(size=50) }}
                            </div>
                        </div>
                        <div class="row device-row">
                            <div class="col-sm-4">
                                {{ form.address.label }}
                            </div>
                            <div class="col-sm-8">
                                {{ form.address(size=50) }}
                            </div>
                        </div>
                        <div class="row device-row">
                            <div class="col-sm-4">
                                {{ form.device_type.label }}
                            </div>
                            <div class="col-sm-8">
                                {{ form.device_type() }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-4">
                            </div>
                            <div class="col-sm-8">
                                {{ form.submit() }}
                            </div>
                        </div>
                    </div>
                </form>

            </div>
            {% if selected %}
                <div class="row">
                    <div id="device-container" class="container-fluid border">
                        <p>{{ selected }}</p>
                    </div>
                </div>
            {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

smart_home/templates/index.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm">
                <h2>Devices</h2>
                <div class="container-fluid border sh-overview-display-container">

                </div>
            </div>
            <div class="col-sm">
                <h3>Monitoring</h3>
                <div class="container-fluid border sh-overview-display-container">

                </div>
            </div>
        </div>
    </div>
{% endblock %}

smart_home/templates/login.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h1>Sign In</h1>
        <p>New User? <a href="{{ url_for('register') }}">Click to Register!</a></p>
        <form action="" method="post" novalidate>
            {{ form.hidden_tag() }}
            <p>
                {{ form.username.label }}<br>
                {{ form.username(size=32) }}
                {% for error in form.username.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
            <p>
                {{ form.password.label }}<br>
                {{ form.password(size=32) }}
                {% for error in form.password.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>
            <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
            <p>{{ form.submit() }}</p>
        </form>

    </div>

{% endblock %}

smart_home/templates/pi.html
{% extends 'base.html' %}

{% block header %}
    <link rel="stylesheet" href="{{ url_for('static',filename='/stylesheets/pi.css') }}">
{% endblock %}
{% block content %}
<div id="pi-container container-fluid">
    <div class="row">
        <div class="col">
            <div id="gpio" class="container">
                <h2>GPIO</h2>
                {% for pin in pins %}
                    <div class="pin-row row">
                        <div class="pin-container container-fluid col">
                            <div class="row">
                                {% if 'GPIO' in pin[0].description %}
                                    <div class="col container-fluid">
                                        <label class="switch">
                                            <input type="checkbox">
                                            <span class="slider"></span>
                                        </label>
                                    </div>


                                {% endif %}
                                <div class="col">
                                    <div class="pin-description">
                                        {{ pin[0].description }}
                                    </div>
                                </div>
                                <div class="col pin-container-left">
                                    <div class="pin">
                                        {{ pin[0].pin }}
                                    </div>

                                </div>
                            </div>
                        </div>
                        <div class="pin-container container-fluid col">
                            <div class="row">
                               <div class="col pin-container-right">
                                   <div class="pin">
                                     {{ pin[1].pin }}
                                   </div>
                                </div>
                                <div class="pin-description col">
                                    <div class="pin-description">
                                        {{ pin[1].description }}
                                    </div>
                                </div>
                                <!-- ON off sliders for pins -->
                                {% if 'GPIO' in pin[1].description %}
                                    <div class="col container-fluid">
                                        <label class="switch">
                                            <input type="checkbox">
                                            <span class="slider"></span>
                                        </label>
                                    </div>


                                {% endif %}

                            </div>
                        </div>

                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="col">
            <h2>Devices</h2>
        </div>
    </div>
</div>

{% endblock %}

smart_home/templates/register.html
{% extends 'base.html' %}

{% block content %}
    <h1>Register</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}<br>
            {% for error in form.username.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.email.label }}<br>
            {{ form.email(size=64) }}<br>
            {% for error in form.email.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password2.label }}<br>
            {{ form.password2(size=32) }}<br>
            {% for error in form.password2.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

smart_home/templates/tasks.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div id="create-task-container" class="col-sm">
                <h2>Create Task</h2>
                <div class="container-fluid border sh-overview-display-container">
                    <form action="" method="post">
                        {{ form.hidden_tag() }}
                        <p>
                            {{ form.device.label }}<br>
                            {{ form.device(size=50) }}
                        </p>
                        <p>
                            {{ form.command.label }}<br>
                            {{ form.command(size=50) }}
                        </p>
                        <p>
                            {{ form.args.label }}<br>
                            {{ form.args(size=150) }}
                        </p>
                        <p>
                            {{ form.queue.label }}<br>
                            {{ form.queue(size=50) }}
                        </p>
                        <p>{{ form.submit() }}</p>


                    </form>
                </div>
            </div>
            <div id="tasks-container" class="col-sm">
                <h3>Tasks:</h3>
                <div class="container-fluid border sh-overview-display-container">

                </div>
            </div>
        </div>
    </div>
{% endblock %}

smart_home/templates/user.html
{% extends "base.html" %}

{% block content %}
    <hr>
    {% for post in posts %}
    <p>
    {{ post.author.username }} says: <b>{{ post.body }}</b>
    </p>
    {% endfor %}
{% endblock %}